### ISSUE TITLE
Cannot find module 'twitter'

### ISSUE THREAD

**Issue by aditya91096** [ideoforms/python-twitter-examples#10]
Hi, I wanted to execute the twitter-search-geo.py file but I get an error which says **'no module named twitter'** even though I have the twitter module in my Scripts directory. I'm using Spyder 3.3.1 on Windows 10. Any help would be appreciated, thanks.

**Comment by ideoforms** [comment]
Hi there, you will need to install the twitter package through your package manager of choice (on Windows, typically either Anaconda or pip).
