### ISSUE TITLE
Number of friends

### ISSUE THREAD

**Issue by a455bcd9** [ideoforms/python-twitter-examples#3]
Hi!

According to this script ( https://github.com/ideoforms/python-twitter-examples/blob/master/twitter-friends.py ) I have 944 friends. This is right ( https://twitter.com/ADssx ). But it actually only prints 924 friends (I only added an index i then print i \ i=i+1).

Thanks for any help you can provide.

**Comment by davidmanheim** [comment]
Just a thought, is it excluding private accounts? (If you use an authenticator that can only see public data, it might not see them.)

**Comment by ideoforms** [comment]
A bit late now probably (!) but I've now resolved this issue - `users.lookup` actually takes a comma-separated string parameter, not a list. Because of the way that Python constructed the URL, the first and last IDs in each set were ignored. Now fixed.
