### ISSUE TITLE
continuation to the above query #5.. twitter-friends.py

### ISSUE THREAD

**Issue by Maheshrocker** [ideoforms/python-twitter-examples#6]
I got an error message claiming that my account is suspended after running this script..

Is there anything this script got to do or is there anything that i could have possible done wrong ??

Thanks in advance

**Comment by beatrizChagas** [comment]
what the error code that was returned? have you accessed the twitter account, identified some wrong? Because the code looks right.

**Comment by Maheshrocker** [comment]
hi. when i execute twitter-friends.py i am getting as 1043 friends. but my account is a relatively new account. what does friends mean?. i have just one follower.

and i get this after running it.
Traceback (most recent call last):
File "twitter-friends.py", line 17, in
exec("config.py", config)
File "", line 1, in
NameError: name 'config' is not defined
hduser@localhost:$ vi twitter-friends.py
hduser@localhost:$ python twitter-friends.py
Traceback (most recent call last):
File "twitter-friends.py", line 18, in
exec("config.py".read(), config)
AttributeError: 'str' object has no attribute 'read'
hduser@localhost:$ vi twitter-friends.py
hduser@localhost:$ python twitter-friends.py
found 1043 friends
Traceback (most recent call last):
File "/home/hduser/anaconda3/lib/python3.6/site-packages/twitter/api.py", line 319, in _handle_response
handle = urllib_request.urlopen(req, **kwargs)
File "/home/hduser/anaconda3/lib/python3.6/urllib/request.py", line 223, in urlopen
return opener.open(url, data, timeout)
File "/home/hduser/anaconda3/lib/python3.6/urllib/request.py", line 532, in open
response = meth(req, response)
File "/home/hduser/anaconda3/lib/python3.6/urllib/request.py", line 642, in http_response
'http', request, response, code, msg, hdrs)
File "/home/hduser/anaconda3/lib/python3.6/urllib/request.py", line 570, in error
return self._call_chain(*args)
File "/home/hduser/anaconda3/lib/python3.6/urllib/request.py", line 504, in _call_chain
result = func(*args)
File "/home/hduser/anaconda3/lib/python3.6/urllib/request.py", line 650, in http_error_default
raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "twitter-friends.py", line 62, in
subquery = twitter.users.lookup(user_id = ids)
File "/home/hduser/anaconda3/lib/python3.6/site-packages/twitter/api.py", line 312, in call
return self._handle_response(req, uri, arg_data, _timeout)
File "/home/hduser/anaconda3/lib/python3.6/site-packages/twitter/api.py", line 345, in _handle_response
raise TwitterHTTPError(e, uri, self.format, arg_data)
twitter.api.TwitterHTTPError: Twitter sent status 403 for URL: 1.1/users/lookup.json using parameters: (oauth_consumer_key=9BPT2QqaGyV9ZvSGwjhVMqMMC&oauth_nonce=9450269275235606841&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1497530423&oauth_token=2983687160-UrIWQUZK5bbNY9e3Xx9GNZe1OfnUSuE1y3NwF0L&oauth_version=1.0&user_id=%5B1541364193%2C%20378152930%2C%201001674602%2C%2046407661%2C%20338174945%2C%204256170955%2C%2076025806%2C%20128334909%2C%204766003668%2C%20472364403%2C%20776725314%2C%20113168001%2C%20839066041208700929%2C%204258018137%2C%20325766424%2C%201595809370%2C%2022277505%2C%20137118269%2C%20397420741%2C%20367331132%2C%2037489372%2C%203299192225%2C%2018505218%2C%2017090112%2C%20629133%2C%20427696547%2C%202289160027%2C%202976625727%2C%20738538436%2C%20813286%2C%20824473943931293697%2C%2044401576%2C%202999158160%2C%203240143771%2C%202354677800%2C%20237920763%2C%20724171756198608896%2C%20140474586%2C%204661872176%2C%204435227552%2C%20728208660887949313%2C%206792522%2C%201473686120%2C%20160952087%2C%2084038687%2C%20732649152807469056%2C%202869819060%2C%201395320539%2C%201689419970%2C%20510782766%2C%203051229241%2C%20522519631%2C%20756124634186125316%2C%20117115913%2C%202928256157%2C%20710433071313625090%2C%20163689916%2C%20251293035%2C%2015862718%2C%20108140114%2C%20891363019%2C%20222834258%2C%2040931468%2C%203303552016%2C%20741195905685172225%2C%203723167245%2C%20726132381615296512%2C%202907774137%2C%2021588148%2C%2017618048%2C%20226424062%2C%202571133226%2C%202818053218%2C%20278134862%2C%20534637926%2C%204305615136%2C%20245548093%2C%2015178534%2C%202201413052%2C%20519419544%2C%20514396066%2C%201294741%2C%2019587466%2C%203364327647%2C%202360459340%2C%20779416353019203584%2C%20123395124%2C%20733813%2C%20741199962474741760%2C%2030149760%2C%20410034621%2C%20249319425%2C%201191261350%2C%2084623872%2C%202505504208%2C%203107896458%2C%2028406270%2C%20741205276905377797%2C%20105826626%2C%203571233797%5D&oauth_signature=ikUP0TaAbOuyisJsy7r0ysasp%2FA%3D)
details: {'errors': [{'code': 64, 'message': 'Your account is suspended and is not permitted to access this feature.'}]}

Any help would be appreciated

**Comment by ideoforms** [comment]
If you exceed the Twitter API's rate limits by making excessive queries, your account may be limited or suspended.

Closing this ticket as it does not relate to a bug within the code.
